### ISSUE TITLE
OCS issue when stopping and then restarting nodes

### ISSUE THREAD

**Issue by dudash** [jaredhocutt/openshift-provision#15]
I had a storage mapping issue in my 3.9 cluster in a stop/restart scenario. Basically, I stop all the nodes at night and sometimes leave them off for over a week. When I restart some (all?) of the PVCs have issues coming back up correctly and I need to recreate the PVs for them to use.

I don't have logs right now, but I wanted to start a discussion to track this and triage/diagnose and potentially collect data for writing an upstream bug. I'm assuming it's not something weird on my cluster and am pretty sure it doesn't actually have anything to do with this openshift-provisioner either.

**Comment by jaredhocutt** [comment]
This is unfortunately a known issue for OCS 3.9. The issue was raised upstream and is the reason OCS 3.10 was delayed from being released at the same time as OpenShift 3.10 in order to solve the problems.

I'm not sure if the fixes have been backported to OCS 3.9 yet or not.

My hope is that the fixes are backported and I can leave the OpenShift and OCS versions matched up (i.e. OCP 3.9 with OCS 3.9 and OCP 3.10 with OCS 3.10). If they do not get backported, my understanding is that OCS 3.10 is tested to work with OpenShift 3.9 and I will update the installer to use the newer OCS 3.10 in order to fix the issue.
