### ISSUE TITLE
Unable to deploy openshift

### ISSUE THREAD

**Issue by ajay-kumar-1** [jaredhocutt/openshift-provision#33]
Hello All,

I am using this procedure to deploy the openshift on aws instance.

On below executing the below command, i am getting in trouble,
./op.py --env-file vars/aws.example.env --vars-file vars/aws.example.yml provision

I am obtaining the below error message:

TASK [provision_aws : Create master instance(s)] **********************************************************************
Friday 08 March 2019  13:45:25 +0000 (0:00:00.925)       0:00:12.789 **********
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:
Instance creation failed => AuthFailure: Not authorized for images: [ami-0d70a070]

However, I has successfully configure the "aws configure command".

Can you help me on this?

**Comment by jaredhocutt** [comment]
That RHEL AMI ID is one of the Cloud Access images and requires you to have Cloud Access enabled for your AWS account.

The details for getting that setup for your account is here: https://access.redhat.com/public-cloud

To workaround it for now, you can switch the tool to use the hourly RHEL AMIs by setting:

```yaml
ec2_ami_type: hourly
```

**Comment by ajay-kumar-1** [comment]
Hi Jaredhocutt,

Thanks for your response.

I am very new to openShift and AWS infrastructure.
Above suggestion work for me, but now i am stuck on the below message:

TASK [provision_aws : Create DNS entry for bastion] *******************************************************************
Saturday 09 March 2019  04:51:07 +0000 (0:00:00.042)       0:01:27.506 ********
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

[RRSet with DNS name bastion.openshift.example.com. is not permitted in zone master.openshift.com.]

Can you guide me on this also?

**Comment by jaredhocutt** [comment]
@AjayKumar333 If you're very new to OpenShift, I'd recommend starting with `minishift` as it's a much better tool for getting started and learning OpenShift.

Here's the link for `minishift`: https://developers.redhat.com/products/cdk/download/

This tool requires you to have an OpenShift subscription from Red Hat in order to deploy it.

---

The specific error you're hitting is because you did not update the variables with values that match your environment in the variable file. You would need to set `openshift_base_domain` to a domain that you own (instead of `example.com`) and also already have that domain configured in Route53. You would also need to update `route53_hosted_zone_id` to be the hosted zone ID of the domain you have configured in Route53.
