### ISSUE TITLE
RFE - add UUID tag 

### ISSUE THREAD

**Issue by jduncan-rva** [jaredhocutt/openshift-provision#4]
Could take the tag from a var or the name of the key or something. But in a multi-tenant environment, it'd be nice to differentiate more easily between volumes.

**Comment by jaredhocutt** [comment]
I currently add a few tags to the EBS volumes that get created when provisioning the nodes.

Key | Value
-- | --
Name | openshift-example-com-app01
OpenShiftClusterName | openshift
OpenShiftClusterNameVerbose | openshift-example-com
OpenShiftRole | app

Do these tags satisfy what you're looking for?

**Comment by jduncan-rva** [comment]
Yeah, I saw those. 
I like how {{ cluster_name }} is used to create the DNS entry. The downside of this method is that each cluster requires you to edit your vars file. 

Thinking through to workshop content (if we use this for workshops) this would be tedious. It's also annoying for lazy people who may need multiple test clusters but don't like to edit files. Third use case would be triggering this through Tower in an automated fashion. 

The name is great. But something like: 

* `<OpenShiftClusterName>-<6-digit hash>.<Domain>`
* `<OpenShiftClusterName>-<Epoch Date>.<Domain>`

would make it easier to deploy multiple clusters and not have to edit vars.

**Comment by jaredhocutt** [comment]
You will have to provide some bit of information each time you spin up a new cluster. The tool needs to know what URL to use and it needs to be unique for the cluster.

Since the URL will always be unique for a cluster, it is effectively a UUID.

For how I handle this for my own so I don't have to copy a bunch of files each time, I have the following:

```bash
vars
├── aws.redhatgov.env  # I re-use this for all clusters in the shared account
├── aws.redhatgov.yml  # This has everything except the cluster_name in it
├── aws.rdht.env       # I re-use this for all clusters in my account
└── aws.rdht.yml       # This has everything except the cluster_name in it
```

Then for each new cluster, I add the `-e cluster_name=clusterX` when running the `ansible-playbook` commands. That lets me keep a set of common files and quickly create unique clusters. Associating it back to your example, this should let you be lazy by specifying just one value when running the playbooks and in Tower, you would only need to prompt for a single string for `cluster_name`.

Does that approach work well for what you're trying to do or am I still missing the nail?

**Comment by jduncan-rva** [comment]
maybe.

let's close this for now.
